import type { Metadata } from 'next';
import './globals.css';


export const metadata: Metadata = {
    title: 'My portfolio',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`antialiased bg-slate-900`}>
                <div
                    className='pointer-events-none fixed inset-0 z-30 transition duration-300 lg:absolute'
                    style={{
                        background: 'radial-gradient(600px at 0px 0px, rgba(29, 78, 216, 0.15), transparent 80%)',
                    }}
                ></div>
                {children}
            </body>
        </html>
    );
}
